export const SIGNUP_CHANGE_VALIDATE = "SIGNUP_CHANGE_VALIDATE";
export const MAKE_CHANGE_SIGNUP = "MAKE_CHANGE_SIGNUP";
export const SUBMIT_DATA_SIGNUP = "SUBMIT_DATA_SIGNUP";
export const CLEAR_DATA_SIGNUP = "CLEAR_DATA_SIGNUP";
export const TOGGLE_SEEN = "TOGGLE_SEEN";

export const LOGIN_CHANGE_VALIDATE = "LOGIN_CHANGE_VALIDATE";
export const MAKE_CHANGE_LOGIN = "MAKE_CHANGE_LOGIN";
export const SUBMIT_DATA_LOGIN = "SUBMIT_DATA_LOGIN";
export const TOGGLE_SEEN_LOGIN = "TOGGLE_SEEN_LOGIN";
export const CLEAR_DATA_LOGIN = "CLEAR_DATA_LOGIN";

export const ON_CHANGE_SEARCH = "ON_CHANGE_SEARCH";
export const UPDATE_RECENT_TAB = "UPDATE_RECENT_TAB";
